### ISSUE TITLE
Debate: the reasoning behind "Avoid if Expressions"

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/erlang_guidelines#14]
[This rule](https://github.com/inaka/erlang_standards#avoid-if-expressions) needs improvement

**Comment by unbalancedparentheses** [comment]
Although  ```if``` can be useful in some cases, I don't like having many ways of doing the same thing or thinking about it :P.

PD: Check http://rvirding.blogspot.se/2008/11/erlang-rationale-problem-with-if.html

**Comment by elbrujohalcon** [comment]
This discussion is long dead. I'll close the ticket.

**Comment by pierre-rouleau** [comment]
@elbrujohalcon Even if this is closed I believe having a link to Robert Virding's post is more appropriate than having a link to the (currently broken) antiifcampaign.com site.   IMHO the anti-if campaign is not pragmatic enough and does not really apply to Erlang.

**Comment by elbrujohalcon** [comment]
I agree.
