### ISSUE TITLE
Header files: 'should not include' and 'could include'

### ISSUE THREAD

**Issue by amilkr** [inaka/erlang_guidelines#20]
##### rule

>  Header files should not include type definitions nor record definitions nor function definitions.
>  Header files could include macros definitions.

**Comment by elbrujohalcon** [comment]
@amilkr we're still waiting for the PR

**Comment by elbrujohalcon** [comment]
@amilkr …

**Comment by elbrujohalcon** [comment]
@amilkr any time you want, man

**Comment by HernanRivasAcosta** [comment]
@amilkr?
