### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/erlang_guidelines#30]
##### Use standard project structures

> Follow the OTP and community standards for project folder structure.

An individual Erlang application has the following structure when it is meant to conform to OTP conventions:

```
    $APP_ROOT
     |
     -- ebin/          % Contains all generated .beam files.
     -- include/       % Contains all public .hrl files.
     -- priv/          % Contains all other artifacts.
     -- src/           % Contains all .erl files and potentially private
     |                 % .hrl files.
     -- test/          % Contains all EUnit test files.
```

You should use this "flat" directory structure if your project is a simple Erlang application (e.g. a generic component which might be used in other projects) or a library application.

If your system consists of several applications working together, the umbrella project structure should be used,  in which the system root contains a folder named `apps` which will contain the individual application folders. Each application can then have its own `ebin`, `include`, `src` and `test` folders, and the entire project can share resources in the `priv` folder, and dependencies can be downloaded and compiled once for the entire project.

```
    $PROJECT_ROOT
     |
     -- $SYSTEM_ROOT/               % Main system directory.
          |
          -- config/                % Contains all system configuration
          |                         % files and templates.
          -- deps/                  % Contains external applications which
          |    |                    % are used as part of the system.
          |    |
          |    -- some_dep_app/
          -- apps/                  % Contains all applications which are
          |    |                    % part of the system.
          |    |
          |    -- some_app/
          |    -- another_app/
          -- patches/               % Contains all patches to Erlang/OTP
          |                         % which are custom to this system.
          -- priv/                  % Contains all other artifacts.
```

_Reasoning_: All erlang tooling assumes these folder structures, and not following them will cause many errors, especially when working with releases. 

An Erlang system consists of many applications and needs to follow various guidelines in order to be OTP-compliant. This ensures that it is compatible with various utility tools from OTP, e.g. for release generation. In the following lines the directory structure of a project is shown.

**Comment by ukari** [comment]
What is the difference between $PROJECT_ROOT and $SYSTEM_ROOT?
I guess README.md and LICENCE are recommanded to put into $PROJECT_ROOT instead of $SYSTEM_ROOT?

**Comment by igaray** [comment]
@ukari That's correct! the $PROJECT_ROOT is for non-erlang related contents and assets.

**Comment by igaray** [comment]
@elbrujohalcon Can you remember why we reverted the inclusion of the associated PR? Should the PR be modified or this issue be closed?

**Comment by elbrujohalcon** [comment]
I believe it was due to either erlang.mk or rebar3 support for this kind of projects.

**Comment by elbrujohalcon** [comment]
and I believe this should be closed due to rebar3 (the standard tool now) forcing OTP-style folders already.
