### ISSUE TITLE
How do you guys get your funs indented only 2 characters?

### ISSUE THREAD

**Issue by formido** [inaka/erlang_guidelines#49]
Here your `fun` body is only indented 2 characters:

https://github.com/inaka/erlang_guidelines/blob/2d6b36409802682c5cac7f175f5d64b6d000e89b/src/dyn_calls.erl#L10

My erlang-mode indents the bodies of `fun`s 8 characters and when I'm looking at others' source online it usually is, too, like here:

https://github.com/cmullaparthi/ibrowse/blob/d2e369ff42666c3574b8b7ec26f69027895c4d94/test/ibrowse_test_server.erl#L18

I assume most people are using standard erlang-mode formatting.

I much prefer your style. Are you guys hand indenting or using a different IDE or have you hacked on your erlang-mode or something?

**Comment by elbrujohalcon** [comment]
hi @formido, at Inaka each dev uses his own preferred text editor. I use [Sublime Text](http://www.sublimetext.com/) and yeah… I indent functions "by hand", in fact I indent *everything* by hand :trollface:

**Comment by formido** [comment]
Well, that explains it then. If you're only indenting two spaces and preferring few nesting levels, I guess hand indenting isn't too big a chore. :)

Thanks for the quick reply!
