### ISSUE TITLE
Don't leave debugging calls in your source code

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/erlang_guidelines#55]
##### Don't leave debugging calls in your source code
> Unless your project is meant to be run as an escript, there should be no `io:format` nor `ct:pal` calls in your production code (i.e. in the modules inside the `src` folder). Same rule applies for `lager` or `error_logger` calls used just for debugging purposes during test stages.

**Comment by HernanRivasAcosta** [comment]
I agree and I always do:

```
git diff | grep lager
```

Just in case though, I feel logging more than strictly necessary as long as you do it with the proper severity level could be useful to debug issues that arise but you didn't expect. I would assume this rule means no ``lager:notice("reached step 3 of the algorithm, it works!!)`` but keeping reasonable logs is allowed. If that's the case, the rule could use some rewording, if not then I am not fully on board.

**Comment by igaray** [comment]
:+1:

**Comment by jfacorro** [comment]
+1

**Comment by jfacorro** [comment]
If elvis had to detect these things I guess it could only figure out the `io:format`, `ct:pal`. But `error:logger` and `lager:xxx` calls might be just fine in most projects, right?

**Comment by elbrujohalcon** [comment]
@jfacorro yeah… I opened inaka/elvis#270 for that and I specifically wrote `as far as possible` there for that. But this is a rule for humans, here ;)
